-- =====================================================================
-- Supabase Auth 移行 / Phase 2 - 初期 admin ユーザのリンク
-- =====================================================================
-- 目的: Supabase Auth に admin ユーザを作成し、既存 accounts レコードと
--       supabase_user_id でリンクする。
--
-- Phase 1 と同時に実行してもよい (データ変更は 1 行の UPDATE のみ)。
--
-- 手順:
--   1) Supabase Dashboard → Authentication → Users → "Add user"
--      - Email    : 管理者のメール (例: admin@example.com)
--      - Password : 新しい強固なパスワード
--      - Auto Confirm User: ON (メール確認スキップ)
--   2) 作成されたユーザの UUID をコピー
--   3) 下記 SQL の <USER_UUID> と <EMAIL> を書き換えて実行
--   4) ブラウザ index.html を開き、「メールでログイン」から確認
--
-- 注意: 旧 password 列は Phase 1/2 ではそのまま残す (並走期間のため)。
--       admin が Supabase Auth でログインできることを確認してから、
--       他のユーザも順次リンクしていく。
-- =====================================================================

-- ---------------------------------------------------------------------
-- A) 既存 admin レコードを新規 Supabase Auth ユーザにリンク
-- ---------------------------------------------------------------------
-- !! 実行前に <USER_UUID> と <EMAIL> を実際の値に置換してください !!

-- UPDATE accounts
--   SET supabase_user_id = '<USER_UUID>'::uuid,
--       email            = '<EMAIL>',
--       migrated_at      = NOW()
--   WHERE account_type = 'admin'
--     AND supabase_user_id IS NULL
--   LIMIT 1;

-- ---------------------------------------------------------------------
-- B) リンク結果を確認
-- ---------------------------------------------------------------------
-- SELECT id, name, account_type, email, supabase_user_id, migrated_at
--   FROM accounts
--   WHERE supabase_user_id IS NOT NULL;

-- ---------------------------------------------------------------------
-- C) 動作確認 (任意、ログインしたブラウザから)
-- ---------------------------------------------------------------------
-- select * from public.get_my_account();   -- 自分の accounts 行が返れば OK

-- =====================================================================
-- 次ステップ (Phase 3 以降、別計画):
--   * 全ユーザ (sales / tc / promo / custom) を Supabase Auth に移行
--   * accounts.password 列を廃止
--   * RLS ポリシーを厳格化 (supabase_user_id / account_type ベース)
-- =====================================================================
